version: "3.9"

services:
  trailhead:
    image: josiahdc/trailhead:0.35
    build: ./trailhead
    restart: always
    ports:
      - target: 33033
        published: 33033

  switchback:
    image: josiahdc/switchback:0.35
    build: ./switchback
    restart: always
    network_mode: "service:zenith"

  zenith:
    image: josiahdc/zenith:0.35
    build: ./zenith
    restart: always
    privileged: true
