version: "3.9"

services:
    trail:
        image: josiahdc/trail:0.22
        build: ./trail
        ports:
            -   target: 3128
                published: 3128
        restart: always
        privileged: true
